name: rg-pipeline

trigger: none

pool: prabhatpool

steps: 
- task: TerraformInstaller@1
  displayName: task 1 terraform install
  inputs:
    terraformVersion: 'latest'
- script: |
    echo %CD%
    dir
    dir 10june
  displayName: Debug workspace
- task: TerraformTask@5
  displayName: task 2 terraform init
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/'
    backendServiceArm: 'prabhatservicefederation'
    backendAzureRmOverrideSubscriptionID: '582e7b86-d28f-4458-b727-2305c8849192'
    backendAzureRmResourceGroupName: 'prabhatrg'
    backendAzureRmStorageAccountName: 'prabhatstg1'
    backendAzureRmContainerName: '10junecontainer'
    backendAzureRmKey: 'terraform.tfstate'
- task: TerraformTask@5
  displayName: task 3 terraform validate
  inputs:
    provider: 'azurerm'
    command: 'validate'
    workingDirectory: '$(System.DefaultWorkingDirectory)/'
- task: TerraformTask@5
  displayName: task 4 terraform plan
  inputs:
    provider: 'azurerm'
    command: 'plan'
    wworkingDirectory: '$(System.DefaultWorkingDirectory)/'
    environmentServiceNameAzureRM: 'prabhatservicefederation'
- task: TerraformTask@5
  displayName: task 4 terraform apply
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)/'
    commandOptions: '-auto-approve'
    environmentServiceNameAzureRM: 'prabhatservicefederation'
- task: TerraformTask@5
  displayName: task 5 terraform show
  inputs:
    provider: 'azurerm'
    command: 'show'
    workingDirectory: '$(System.DefaultWorkingDirectory)/'
    outputTo: 'console'
    outputFormat: 'default'
    environmentServiceNameAzureRM: 'prabhatservicefederation'